### ISSUE TITLE
CrashLoopBackoff when using ./deploy_hpo.sh -c openshift

### ISSUE THREAD

**Issue by kdelee** [kruize/hpo#136]
Container failing to come up when using `./deploy_hpo.sh -c openshift`

seeing in the logs of container:
```
Traceback (most recent call last):
File "/home/hpo/app/src/service.py", line 18, in <module>
import rest_service, grpc_service
File "/home/hpo/app/src/rest_service.py", line 24, in <module>
from json_validate import validate_trial_generate_json
File "/home/hpo/app/src/json_validate.py", line 1, in <module>
import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

**Comment by kdelee** [comment]
I see `jsonschema` in the requirements and should be getting installe din https://github.com/kruize/hpo/blob/d7e024e2567478c957e52f9b0eee6aa1e5cc0230/Dockerfile.hpo#L55-L56

Wondering why the `entrypoint` appears to be working with docker but not on openshift as far as using right python environment where the package is correctly loaded
