### ISSUE TITLE
Unhandled exception when the status of all the trials in the experiment is prune

### ISSUE THREAD

**Issue by kusumachalasani** [kruize/hpo#17]
Below is the exception observed when the status of all the trials in the experiment is prune
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 919, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 867, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kchalasa/Desktop/em-hpo-scripts/hpo/hpo-l/autotune-demo/hpo/src/bayes_optuna/optuna_hpo.py", line 145, in recommend
    logger.info("Best parameter: " + str(study.best_params))
  File "/home/kchalasa/.local/lib/python3.6/site-packages/optuna/study/study.py", line 60, in best_params
    return self.best_trial.params
  File "/home/kchalasa/.local/lib/python3.6/site-packages/optuna/study/study.py", line 97, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/kchalasa/.local/lib/python3.6/site-packages/optuna/storages/_in_memory.py", line 311, in get_best_trial
    raise ValueError("No trials are completed yet.")
```

**Comment by khansaad** [comment]
It's being handled in the current code. The experiment will gracefully stop.

Please re-test and confirm.

**Comment by kusumachalasani** [comment]
@khansaad 
Tried the hpo demo script, by sending the benchmark_status as "prune" always. 
HPO throws error when the trial_result is passed as prune which is not expected.

```
Send the benchmark results for trial 0
127.0.0.1 - - [19/Jul/2022 15:30:13] "POST /experiment_trials HTTP/1.1" 400 -
curl: (22) The requested URL returned error: 400 Bad Request
2022-07-19 15:30:13 - ERROR - rest_service - Trial result status is invalid!
ERROR: Sending the results to HPO failed.
```
